name: svc-go-color

requires:
  - svc-go-random

config:
  http_port: 8000
  admin_port: 9000

containers:
- dockerfile: docker/Dockerfile
  context: .

profiles:
  stable:
    endpoint: /color/
    admin_endpoint: /color/admin/
    max_memory: 0.5G
    max_cpu: 0.5
  canary:
    endpoint: /color/
    admin_endpoint: /color/admin/
    weight: 10
    max_memory: 0.25G
    max_cpu: 0.25
  default:
    name: {{branch.replace('/', '-')}}
    endpoint: /preview/color/{{branch}}/
    admin_endpoint: /preview/color/{{branch}}/admin/
    max_memory: 0.25G
    max_cpu: 0.25
