apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: 920858517028.dkr.ecr.us-east-1.amazonaws.com/color
deploy:
  kustomize:
    path: './k8s/overlays/development/'
profiles:
- name: with-tests
  test:
    - image: 920858517028.dkr.ecr.us-east-1.amazonaws.com/color
      structureTests:
      - './k8s/structure-tests/*'

