---
apiVersion: v1
kind: Service
metadata:
  name: color
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http-port
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: color-admin
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: admin-port
      protocol: TCP
